/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Aplication.NuevoProveedor;
import java.awt.BorderLayout;

/**
 *
 * @author rohel
 */
public class ListadoProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ListadoProveedores
     */
    public ListadoProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        con_prov = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_buscarproductos = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_listaProductos = new javax.swing.JTable();
        btn_editarcliente = new javax.swing.JButton();
        btn_eliminarcliente = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(966, 488));

        jButton1.setText("Agregar Proveedor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Lista De Proveedor");

        jLabel3.setText("Buscar:");

        btn_buscar.setText("Buscar");

        tabla_listaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_proveedor", "RUC", "Razon Social", "Telefono", "Email", "Direccion"
            }
        ));
        jScrollPane2.setViewportView(tabla_listaProductos);

        btn_editarcliente.setText("Editar");

        btn_eliminarcliente.setText("Eliminar");

        javax.swing.GroupLayout con_provLayout = new javax.swing.GroupLayout(con_prov);
        con_prov.setLayout(con_provLayout);
        con_provLayout.setHorizontalGroup(
            con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
            .addGroup(con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(con_provLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, con_provLayout.createSequentialGroup()
                            .addComponent(btn_editarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(btn_eliminarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jButton1))
                        .addGroup(con_provLayout.createSequentialGroup()
                            .addGroup(con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(con_provLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel3)
                                    .addGap(28, 28, 28)
                                    .addComponent(txt_buscarproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(con_provLayout.createSequentialGroup()
                                    .addGap(344, 344, 344)
                                    .addComponent(jLabel2)))
                            .addGap(58, 58, 58)))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        con_provLayout.setVerticalGroup(
            con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(con_provLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscarproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(btn_buscar))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addGroup(con_provLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(btn_eliminarcliente)
                        .addComponent(btn_editarcliente))
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(con_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(con_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevoProveedor np=new NuevoProveedor();
        np.setSize(966, 448);
        np.setLocation(0,0);
        
        con_prov.removeAll();
        con_prov.add(np, BorderLayout.CENTER);
        con_prov.revalidate();
        con_prov.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editarcliente;
    private javax.swing.JButton btn_eliminarcliente;
    private javax.swing.JPanel con_prov;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_listaProductos;
    private javax.swing.JTextField txt_buscarproductos;
    // End of variables declaration//GEN-END:variables
}
