/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aplication;

/**
 *
 * @author Victoria
 */
public class NuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form cliente
     */
    public NuevoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        con_cliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_sexoC = new javax.swing.JTextField();
        txt_direccionC = new javax.swing.JTextField();
        txt_amaternoC = new javax.swing.JTextField();
        txt_apaternoC = new javax.swing.JTextField();
        txt_nombreC1 = new javax.swing.JTextField();
        txt_emailC = new javax.swing.JTextField();
        txt_tipoc = new javax.swing.JTextField();
        txt_fnacimientoC = new javax.swing.JTextField();
        txt_telefonoC = new javax.swing.JTextField();
        tipo_documento = new javax.swing.JComboBox<>();
        btn_crearcliente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(966, 448));

        con_cliente.setBackground(new java.awt.Color(255, 255, 255));
        con_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nuevo Cliente");
        con_cliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 33, -1, -1));

        jLabel2.setText("Nombre");
        con_cliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setText("Telefono");
        con_cliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel4.setText("Apellido Paterno");
        con_cliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel5.setText("Apellido Materno");
        con_cliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel6.setText("Sexo");
        con_cliente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 20));

        jLabel7.setText("EMAIL");
        con_cliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        jLabel8.setText("Fecha de Nacimiento");
        con_cliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel9.setText("Tipo de documento");
        con_cliente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel10.setText("DNI/Carne de extranjeria");
        con_cliente.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel12.setText("Direccion");
        con_cliente.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));
        con_cliente.add(txt_sexoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 140, -1));

        txt_direccionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionCActionPerformed(evt);
            }
        });
        con_cliente.add(txt_direccionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 140, -1));
        con_cliente.add(txt_amaternoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 140, -1));
        con_cliente.add(txt_apaternoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 140, -1));
        con_cliente.add(txt_nombreC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, -1));
        con_cliente.add(txt_emailC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 140, -1));
        con_cliente.add(txt_tipoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 140, -1));
        con_cliente.add(txt_fnacimientoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 140, -1));
        con_cliente.add(txt_telefonoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 140, -1));

        tipo_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "PASAPORTE", "CARNET DE EXTRANJERIA" }));
        con_cliente.add(tipo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 140, -1));

        btn_crearcliente.setText("Crear");
        btn_crearcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearclienteActionPerformed(evt);
            }
        });
        con_cliente.add(btn_crearcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(con_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(con_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_direccionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionCActionPerformed

    private void btn_crearclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crearcliente;
    private javax.swing.JPanel con_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> tipo_documento;
    private javax.swing.JTextField txt_amaternoC;
    private javax.swing.JTextField txt_apaternoC;
    private javax.swing.JTextField txt_direccionC;
    private javax.swing.JTextField txt_emailC;
    private javax.swing.JTextField txt_fnacimientoC;
    private javax.swing.JTextField txt_nombreC1;
    private javax.swing.JTextField txt_sexoC;
    private javax.swing.JTextField txt_telefonoC;
    private javax.swing.JTextField txt_tipoc;
    // End of variables declaration//GEN-END:variables
}
