/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aplication;

/**
 *
 * @author Usuario
 */
public class NuevoProveedor extends javax.swing.JPanel {

    /**
     * Creates new form NuevoProveedor
     */
    public NuevoProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        con_proveedor = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        con_proveedor.setBackground(new java.awt.Color(255, 255, 255));
        con_proveedor.setPreferredSize(new java.awt.Dimension(966, 420));
        con_proveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        con_proveedor.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, 30));

        jLabel1.setText("RUC");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 170, 170));
        con_proveedor.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 130, 30));

        jLabel2.setText("Razon Social");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 120, 30));
        con_proveedor.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, 30));

        jLabel3.setText("Nombre Comercial");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 30));

        jLabel4.setText("Direccion");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, 30));
        con_proveedor.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 130, 30));

        jLabel5.setText("Teléfono");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 30));
        con_proveedor.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 30));

        jLabel6.setText("Estado");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, 30));
        con_proveedor.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 170, 30));

        jLabel7.setText("Email");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Activo", "No Activo" }));
        con_proveedor.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 30));

        jLabel8.setText("RUC");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_proveedor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 30));
        con_proveedor.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 130, 30));

        jButton1.setText("Añadir FOTO");
        con_proveedor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(con_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(con_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel con_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
